import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Divider, Grid, Typography } from '@mui/material'
import { TermCard } from '@/components/Term/TermCard'
import Link from 'next/link'
import { Term } from '@/types'

const inter = Inter({ subsets: ['latin'] })

const term: Term = {
	id: '1',
	title: 'advance',
	translate: 'avanzar',
	level: 'Easy',
	category: 'Come',
	user: '',
	phrases: [''],
}
export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Grid container>
				<Grid item xs={4}></Grid>
				<Grid item xs={4}>
					<Typography variant="h2">Glossary Cards</Typography>
					<Divider />
					<TermCard term={term} />
					<Link
						href={'/term/63d9c8cc2b7ab008548d7521'}
						className={styles.buttonNext}
					>
						Next Term
					</Link>
				</Grid>
				<Grid item xs={4}></Grid>
			</Grid>
		</>
	)
}
